### ISSUE TITLE
Update flowpack/listable

### ISSUE THREAD

**Issue by mstruebing** [webexcess/WebExcess.Comments#33]
Because flowpack/listable is only usable with Neos ^3.0 and not 4.0.
see: https://packagist.org/packages/flowpack/listable#v2.0.1

**Comment by sbruggmann** [comment]
There's a PR hanging which is still not tested, sorry: #32

Does this work in your environment as expected?

**Comment by mstruebing** [comment]
I will test this asap but priorities did change right now

**Comment by sbruggmann** [comment]
PR #32 is finally merged
